### ISSUE TITLE
Closing a Window via the close button does not unset the hot region

### ISSUE THREAD

**Issue by sdleffler** [coding-jackalope/Slab#33] opened 2020-06-27 04:24 UTC
When closing a window via the close button, if `BeginWindow` is not later called with `IsOpen = false` (going from `BeginWindow(... { ... IsOpen = true ... })` to not calling `BeginWindow` at all but still calling `Slab.Update`) then the `Region.HotInstance` variable remains set to the now closed window and does not get corrected until another Slab object is hovered over and then unhovered. This interferes badly with `Slab.IsVoidHovered`.

**Comment by sdleffler** [comment] 2020-06-27 04:33
Proposed fix: provide a `Region.Obstruct()` function which checks to see if the active region is the hot region, and if so, nils the hot region. This can be called from the same block in `Window.lua` which checks to see if the close button is clicked:

```lua
			if IsCloseHovered then
				DrawCommands.Circle(
					'fill',
					CloseX,
					CloseY,
					CloseBgRadius,
					Style.WindowCloseBgColor
				)

				if Mouse.IsClicked(1) then
					ActiveInstance.IsOpen = false
					Options.IsOpen = false
					ActiveInstance.IsMoving = false
					
					Region.Obstruct()
				end
			end```

**Comment by sdleffler** [comment] 2020-06-27 16:44
I think I've found a better solution - this seems to be solved more neatly and robustly by adding a frame number counter to `Region` in a similar manner to `Window`, and then in `Region.GetHotInstance` we can check whether or not the hot instance has been updated within the last couple frames; if not, nil it out and return the empty string. This makes `Region.Obstruct()` unnecessary and should solve the ghost-hot-region issue at its source.

**Comment by coding-jackalope** [comment] 2020-06-29 19:39
Hi @sdleffler thanks for reporting this issue. I was able to reproduce this and have checked in a fix. You can see the commit at 5395f26. This fix will be added to the next update.

I went with keeping the frame number in Window since it is used to update what windows are visible and their stack order. I added a function to clear the hot region if the given window has been removed from the stack. This is handled in Window.Validate which is called every Draw before the actual rendering occurs.

**Closed** 2020-07-23 19:23 UTC
